import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Three example',
  description: 'Generated by create next app'
}

export default function ThreeLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex h-[calc(100vh-theme(spacing.16))] items-center justify-center py-10">
      {children}
    </div>
  )
}
